### ISSUE TITLE
Upgrade mlflow to 1.23.1 or higher

### ISSUE THREAD

**Issue by heidmic** [heidmic/suprb-experimentation#19]
"mlflow prior to 1.23.1 contains an insecure temporary file. The insecure function tempfile.mktemp() is deprecated and mkstemp() should be used instead."

fit: * add mlflow>=1.23.1 to requirements
* test if functionality is unchanged

@hubanton could you test this asap please as it is accutely relevant for you?

**Comment by hubanton** [comment]
Used mlflow version 1.23.1 performing Evalution on 64 runs. Program ran as usual and the output was as excepted (also works fine when using mlflow ui)

**Comment by heidmic** [comment]
Thanks! Will update the requirements right away
